/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import org.openqa.selenium.Alert;

import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {

        //TODO: call your test case functions one after other here

//        AmazonSearch amazonSearch = new AmazonSearch();
//        amazonSearch.testCase01();

//        CountHyperlink countHyperlink = new CountHyperlink();
//        countHyperlink.testCase01();

//        PostOnLinkedIn postOnLinkedIn = new PostOnLinkedIn();
//        postOnLinkedIn.testCase01();

//        NameGoogleSearch nameGoogleSearch = new NameGoogleSearch();
//        nameGoogleSearch.testCase01();

//        BMSImgUrls bmsImgUrls = new BMSImgUrls();
//        bmsImgUrls.testCase01();

//        NestedFramesText nestedFramesText = new NestedFramesText();
//        nestedFramesText.testCase01();

//        AlertPromt alertPromt = new AlertPromt();
//        alertPromt.testCase01();

//        IMDBRating imdbRating = new IMDBRating();
//        imdbRating.testCase01();

        WindowHandle windowHandle = new WindowHandle();
        windowHandle.testCase01();

        //END Tests
//        amazonSearch.endTest(); // End your test by cleaning connections and closing browser
//        countHyperlink.endTest();
//        postOnLinkedIn.endTest();
//        nameGoogleSearch.endTest();
//        bmsImgUrls.endTest();
//        nestedFramesText.endTest();
//        alertPromt.endTest();
//        imdbRating.endTest();
        windowHandle.endTest();
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
